module.exports = {
  username: process.env.LIT_USER,
  password: process.env.LIT_PASS,
  url: process.env.LIT_URL,
  applications: [
    'appmail7',
    'appmail8',
    'iphone5s',
    'ipadmini',
    'ipad',
    'gmailnew',
    'ffgmailnew',
    'chromegmailnew',
    'iphone6',
    'iphone6plus',
    'ol2003',
    'ol2007',
    'ol2010',
    'ol2011',
    'ol2013',
    'outlookcom',
    'ffoutlookcom',
    'chromeoutlookcom',
    'yahoo',
    'ffyahoo',
    'chromeyahoo',
    'androidgmailapp'
    // 'android22',
    // 'android4',
    // 'aolonline',
    // 'ffaolonline',
    // 'chromeaolonline',
    // 'blackberry8900',
    // 'blackberryhtml',
    // 'colorblind',
    // 'barracuda',
    // 'spamassassin3',
    // 'gmailnewspam',
    // 'notes6',
    // 'notes7',
    // 'notes8',
    // 'notes85',
    // 'ol2000',
    // 'ol2002',
    // 'plaintext',
    // 'thunderbirdlatest',
    // 'windowsphone8'
  ]
};